services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server-symfony
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - db
      - mailer
    networks:
      - symfony_net

  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 30s
      retries: 3

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
