services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server-symfony
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - db
    networks:
      - symfony_net

  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
