services:
  web:
    image: php:8.2-apache
    container_name: server
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/apacheConf.txt:/etc/apache2/sites-available/000-default.conf
    command: >
      bash -c "a2enmod rewrite &&
               ln -sf /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/000-default.conf &&
               apache2ctl -D FOREGROUND"
    environment:
      APP_ENV: dev
    depends_on:
      - db
    networks:
      - symfony_net

  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
